---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app     
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app 
    spec:
      containers:
      - name: go-app
        image: endaafiandika/go-app:1 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service                    
metadata:
  name: go-app-service
spec:
  type: NodePort                 
  ports:                         
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: go-app